const Queries = {
    feeds:{
        returnData:`
        id
        creator
        operator
        operatorStatus
        staticMetadata
        staticMetadataB58
        variableMetadata
        variableMetadataB58
        postRegistry
        posts{
            id
        }
        initCallData
        createdTimestamp
        `
    },
    staticMetadataSetFeeds:{
        returnData:`
        id
        instance
        staticMetadata
        staticMetadataB58
        txHash`
    },
    postCreatedFeeds:{
        returnData:`
        id
        instance
        post
        postFactory
        initData
        timestamp
        txHash`
    },
    variableMetadataSetFeeds:{
        returnData:`
        id
        instance
        variableMetadata
        variableMetadataB58
        timestamp
        txHash`
    },
    operatorUpdatedFeeds:{
        returnData:`
        id
        instance
        operator
        status
        timestamp
        txHash`
    },
    posts:{
        returnData: `id
        feed
        {
            id
        }
        creator
        operator
        operatorStatus
        staticMetadata
        staticMetadataB58
        variableMetadata
        variableMetadataB58
        proofHash
        initCallData
        createdTimestamp`
    },
    instanceCreatedPostFactories:{
        returnData:`
        id
        instance
        creator
        callData
        timestamp
        txHash`
    },
    postCreatedPosts:{
        returnData:`
        id
        instance
        operator
        proofHash
        staticMetadata
        staticMetadataB58
        variableMetadata
        variableMetadataB58
        timestamp
        txHash
        `
    },
    variableMetadataSetPosts:{
        returnData:`
        id
        instance
        variableMetadata
        variableMetadataB58
        timestamp
        txHash
        `
    },
    staticMetadataSetPosts:{
        returnData:`
        id
        instance
        staticMetadata
        staticMetadataB58
        timestamp
        txHash
        `
    },
    operatorUpdatedPosts:{
        returnData:`
        id
        instance
        operator
        status
        timestamp
        txHash`
    },
    proofHashSetPosts:{
        returnData:`
        id
        instance
        caller
        proofHash
        timestamp
        txHash`
    },
    //one way griefing
    oneWayGriefingAgreements:{
        returnData:`
        id
        creator
        counterparty
        operator
        operatorStatus
        ratio
        ratioType
        staticMetadata
        staticMetadataB58
        variableMetadata
        variableMetadataB58
        stake
        token
        deadline
        initCallData
        createdTimestamp
        `
    },
    variableMetadataSetOneWayGriefings:{
        returnData:`
        id
        instance
        variableMetadata
        variableMetadataB58
        timestamp
        txHash
        `
    },
    instanceCreatedOneWayGriefingFactories:{
        returnData:`
        id
        instance
        creator
        callData
        timestamp
        txHash`
    },
    staticMetadataSetOneWayGriefings:{
        returnData:`
        id
        instance
        staticMetadata
        staticMetadataB58
        timestamp
        txHash
        `
    },
    operatorUpdatedOneWayGriefings:{
        returnData:`
        id
        instance
        operator
        status
        timestamp
        txHash
        `
    },
    ratioSetOneWayGriefings:{
        returnData:`
        id
        instance
        ratio
        ratioType
        timestamp
        txHash`
    },
    griefedOneWayGriefings:{
        returnData:`
        id
        instance
        punisher
        punishment
        cost
        message
        timestamp
        txHash`
    },
    tokenSetOneWayGriefings:{
        returnData:`
        id
        instance
        token
        timestamp
        txHash
        `
    },
    stakeAddedOneWayGriefings:{
        returnData:`
        id
        instance
        staker
        funder
        amount
        newStake
        timestamp
        txHash
        `
    },
    stakeTakenOneWayGriefings:{
        returnData:`
        id
        instance
        staker
        recipient
        amount
        newStake
        timestamp
        txHash`
    },
    stakeBurnedOneWayGriefings:{
        returnData:`
        id
        instance
        staker
        amount
        newStake
        timestamp
        txHash`
    },
    lengthSetOneWayGriefings:{
        returnData:`
        id
        instance
        length
        timestamp
        txHash
        `
    },
    deadlineSetOneWayGriefings:{
        returnData:`
        id
        instance
        deadline
        timestamp
        txHash`
    }

}

module.exports = Queries