const Queries = {
    feeds:{
        returnData:`
        id
        creator
        operator
        operatorStatus
        staticMetadata
        staticMetadataB58
        variableMetadata
        variableMetadataB58
        postRegistry
        posts
        initCallData
        createdTimestamp
        `
    },
    staticMetadataSetFeeds:{
        returnData:`
        id
        instance
        staticMetadata
        staticMetadataB58
        txHash`
    },
    postCreatedFeeds:{
        returnData:`
        id
        instance
        post
        postFactory
        initData
        timestamp
        txHash`
    },
    variableMetadatSetFeeds:{
        returnData:`
        id
        instance
        variableMetadata
        variableMetadataB58
        timestamp
        txHash`
    },
    opreatorUpdateFeeds:{
        returnData:`
        id
        instance
        operator
        status
        timestamp
        txHash`
    },
    posts:{
        returnData: `id
        feed
        creator
        operator
        operatorStatus
        staticMetadata
        staticMetadataB58
        variableMetadata
        variableMetadataB58
        proofHash
        initCallData
        createdTimestamp`
    },
    instanceCreatePostFactories:{
        returnData:`
        id
        instance
        creator
        callData
        timestamp
        txHash`
    },
    postCreatedPosts:{
        returnData:`
        id
        instance
        operator
        proofHash
        staticMetadata
        staticMetadataB58
        variableMetadata
        variableMetadataB58
        timestamp
        txHash
        `
    },
    variableMetadataSetPosts:{
        returnData:`
        id
        instance
        variableMetadata
        variableMetadataB58
        timestamp
        txHash
        `
    },
    staticMetadataSetPosts:{
        returnData:`
        id
        instance
        staticMetadata
        staticMetadataB58
        timestamp
        txHash
        `
    },
    operatorUpdatePosts:{
        returnData:`
        id
        instance
        oeprator
        status
        timestamp
        txHash`
    },
    proofHashSetPost:{
        returnData:`
        id
        instance
        caller
        proofHash
        timestamp
        txHash`
    },
    //one way griefing
    oneWayGriefingAgreements:{
        returnData:`
        id
        creator
        staker
        counterparty
        operator
        operatorStatus
        ratio
        ratioType
        countDownLength
        staticMetadata
        staticMetadataB58
        variableMetadata
        variableMetadataB58
        statke
        token
        deadline
        initCallData
        createdTimestamp
        `
    },
    variableMetadataSetOneWayGriefings:{
        returnData:`
        id
        instance
        variableMetadata
        variableMetadataB58
        timestamp
        txHash
        `
    },
    instanceCreatedOneWayGriefingFactories:{
        returnData:`
        id
        instance
        creator
        callData
        timestamp
        txHash`
    },
    staticMetadataSetOneWayGriefings:{
        returnData:`
        id
        instance
        staticMetadata
        staticMetadataB58
        timestamp
        txHash
        `
    },
    operatorUpdatedOneWayGriefings:{
        returnData:`
        id
        instance
        operator
        status
        timestamp
        txHash
        `
    },
    ratioSetOneWayGriefings:{
        returnData:`
        id
        instance
        staker
        ratio
        ratioType
        timestamp
        txHash`
    },
    griefedOneWayGriefing:{
        returnData:`
        id
        instance
        punisher
        staker
        punishment
        cost
        message
        timestamp
        txHash`
    },
    tokenSetOneWayGriefings:{
        returnData:`
        id
        instance
        token
        timestamp
        txHash
        `
    },
    stakeAddedOneWayGriefings:{
        returnData:`
        id
        instance
        staker
        funder
        amount
        newStake
        timestamp
        txHash
        `
    },
    stakeTakenOneWayGriefing:{
        returnData:`
        id
        instance
        staker
        recipient
        amount
        newStake
        timestamp
        txHash`
    },
    stakeBurnedOneWayGriefings:{
        returnData:`
        id
        instance
        staker
        amount
        newStake
        timestamp
        txHash`
    },
    lengthSetOneWayGriefings:{
        returnData:`
        id
        instance
        length
        timestamp
        txHash
        `
    },
    deadlineSetOneWayGriefing:{
        returnData:`
        id
        instance
        deadline
        timestamp
        txHash`
    }

}

module.exports = Queries